spring:
  application:
    name: QuizApp
  datasource:
    url: jdbc:mysql://localhost:3306/quiz_app_new?createDatabaseIfNotExist=true
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always
  jwt:
    secret: l7GzKcvCOhgtF3rzXmGn08ecP/azxeu88VhNJ+I+XwAQFvhR+HSj+92HnTd5L6cg
    tokenExpiration: 86400
server:
  port: 8080

#logging:
#  level:
#    org.springframework.web: DEBUG
#    org.springframework.security: DEBUG
#    org.springframework.web.filter.CorsFilter: DEBUG

