spring:
  application:
    name: QuizApp
  datasource:
    url: ${url}/quiz_app_new?createDatabaseIfNotExist=true
    username: ${username}
    password: ${password}
  jpa:
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always
  jwt:
    secret: ${secret}
    tokenExpiration: 86400
server:
  port: 8080

#logging:
#  level:
#    org.springframework.web: DEBUG
#    org.springframework.security: DEBUG
#    org.springframework.web.filter.CorsFilter: DEBUG

